### ISSUE TITLE
Please update pip repo

### ISSUE THREAD

**Issue by snnwolf** [iansprice/django-model-changes-py3#1]
Hi.
When `pip install django-model-changes` I have error

`django.db.models.fields.related_descriptors.RelatedObjectDoesNotExist: UserProfile has no user`

I see that U fix this bug, but package has not updated.

**Comment by Ryanb58** [comment]
Wrong Repo. 

```
django-model-changes-py3
```

**Comment by pinguin999** [comment]
Hi @Ryanb58 

if I pip install django-model-changes-py3 the last changes from 
https://github.com/iansprice/django-model-changes-py3/commit/a8e32f480720a42422b7124d3cbf737dc565100c

are not in the package.

Can you update the package, please.

Thanks
Kolja

**Comment by iansprice** [comment]
Thanks, updated
